<a href="https://colab.research.google.com/github/gracenaomi1122/my-first-repo/blob/main/ML_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Load the CarDekho dataset
df = pd.read_csv('cardekho_dataset.csv')

print(f"Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
df.head()

Shape: (15411, 14)
Columns: ['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']

   Unnamed: 0       car_name    brand  ... max_power  seats  selling_price
0           0    Maruti Alto   Maruti  ...     46.30      5         120000
1           1  Hyundai Grand  Hyundai  ...     82.00      5         550000
2           2    Hyundai i20  Hyundai  ...     80.00      5         215000
3           3    Maruti Alto   Maruti  ...     67.10      5         226000
4           4  Ford Ecosport     Ford  ...     98.59      5         570000

[5 rows x 14 columns]

In [ ]:
df = df.drop(columns=['Unnamed: 0', 'car_name', 'model'])
print(f"Shape after dropping: {df.shape}")
print(f"Remaining columns: {df.columns.tolist()}")

Shape after dropping: (15411, 11)
Remaining columns: ['brand', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']

In [ ]:
df

          brand  vehicle_age  km_driven  ... max_power seats selling_price
0        Maruti            9     120000  ...     46.30     5        120000
1       Hyundai            5      20000  ...     82.00     5        550000
2       Hyundai           11      60000  ...     80.00     5        215000
3        Maruti            9      37000  ...     67.10     5        226000
4          Ford            6      30000  ...     98.59     5        570000
...         ...          ...        ...  ...       ...   ...           ...
15406   Hyundai            9      10723  ...     68.05     5        250000
15407    Maruti            2      18000  ...     91.10     7        925000
15408     Skoda            6      67000  ...    103.52     5        425000
15409  Mahindra            5    3800000  ...    140.00     7       1225000
15410     Honda            2      13000  ...    117.60     5       1200000

[15411 rows x 11 columns]

In [ ]:
# One-hot encode all categorical columns
df = pd.get_dummies(df, columns=['brand', 'seller_type', 'fuel_type',
                                  'transmission_type'], drop_first=True)

print(f"Shape after encoding: {df.shape}")
print(f"Sample of new columns: {[c for c in df.columns if '_' in c][:10]}")
df

Shape after encoding: (15411, 45)
Sample of new columns: ['vehicle_age', 'km_driven', 'max_power', 'selling_price', 'brand_BMW', 'brand_Bentley', 'brand_Datsun', 'brand_Ferrari', 'brand_Force', 'brand_Ford']

       vehicle_age  km_driven  ...  fuel_type_Petrol  transmission_type_Manual
0                9     120000  ...              True                      True
1                5      20000  ...              True                      True
2               11      60000  ...              True                      True
3                9      37000  ...              True                      True
4                6      30000  ...             False                      True
...            ...        ...  ...               ...                       ...
15406            9      10723  ...              True                      True
15407            2      18000  ...              True                      True
15408            6      67000  ...             False                      True
15409            5    3800000  ...             False                      True
15410            2      13000  ...              True                     False

[15411 rows x 45 columns]

In [ ]:
X = df.drop(columns=['selling_price'])
y = df['selling_price']

print(f"Features: {X.shape[0]} rows × {X.shape[1]} columns")
print(f"Target: selling_price — ₹{y.min():,} to ₹{y.max():,}")
print(f"Target mean: ₹{y.mean():,.0f}, median: ₹{y.median():,.0f}")

Features: 15411 rows × 44 columns
Target: selling_price — ₹40,000 to ₹39,500,000
Target mean: ₹774,971, median: ₹556,000

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train: {X_train.shape[0]} rows ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Test:  {X_test.shape[0]} rows ({X_test.shape[0]/len(X)*100:.0f}%)")

Train: 12328 rows (80%)
Test:  3083 rows (20%)

In [ ]:
numeric_cols = ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

scaler = StandardScaler() # MinMaxsclar()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])  # fit + transform on TRAIN
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])         # only transform on TEST

print("After scaling (train set):")
print(X_train[numeric_cols].describe().round(2).loc[['mean', 'std']])
print("\n✅ Mean ≈ 0, Std ≈ 1 for all numeric features")

After scaling (train set):
      vehicle_age  km_driven  mileage  engine  max_power  seats
mean          0.0       -0.0      0.0    -0.0        0.0   -0.0
std           1.0        1.0      1.0     1.0        1.0    1.0

✅ Mean ≈ 0, Std ≈ 1 for all numeric features

In [ ]:
X_train

       vehicle_age  km_driven  ...  fuel_type_Petrol  transmission_type_Manual
11210     0.323969   0.349100  ...             False                     False
1347     -1.337798  -1.069394  ...              True                      True
10363    -1.337798  -1.163564  ...             False                     False
316       0.323969   0.178369  ...              True                      True
10638     1.321030   0.585469  ...              True                      True
...            ...        ...  ...               ...                       ...
5191      0.323969   1.702310  ...             False                      True
13418     1.653383   0.084198  ...              True                      True
5390      0.323969  -0.833967  ...              True                      True
860      -1.337798  -0.951680  ...              True                      True
7270     -1.337798  -0.598540  ...              True                     False

[12328 rows x 44 columns]

# ML model

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.coef_

array([-2.27679116e+05, -4.61441160e+04, -1.61215737e+04,  7.81262973e+04,
        3.35373847e+05,  3.61447730e+04,  4.05858369e+05,  3.66129519e+06,
       -7.09797494e+05,  3.35712157e+07, -6.84161881e+05, -6.05929376e+05,
       -6.34461348e+05, -5.81777427e+05, -5.39248828e+05, -6.72399952e+05,
        3.89829810e+05, -3.30328774e+05, -1.88217266e+05,  1.37973826e+06,
        2.43851701e+06, -3.34953252e+05, -7.57351045e+05, -5.09629233e+05,
        3.05324950e+06, -3.72529030e-09,  2.12192715e+05,  5.81734336e+05,
       -6.92637218e+05,  1.83113118e+06, -6.41815125e+05,  1.83478941e+07,
       -6.76533456e+05, -8.25722441e+05, -4.17293997e+05, -6.20822305e+05,
        1.07324564e+06, -1.20906369e+04, -8.11214717e+04,  4.90755661e+04,
        2.93031384e+05,  2.77714921e+05, -4.11245704e+04, -5.92492214e+04])

In [ ]:
model.intercept_

np.float64(1324658.8210497976)

# Performace Metircs

In [ ]:
X_train

       vehicle_age  km_driven  ...  fuel_type_Petrol  transmission_type_Manual
11210     0.323969   0.349100  ...             False                     False
1347     -1.337798  -1.069394  ...              True                      True
10363    -1.337798  -1.163564  ...             False                     False
316       0.323969   0.178369  ...              True                      True
10638     1.321030   0.585469  ...              True                      True
...            ...        ...  ...               ...                       ...
5191      0.323969   1.702310  ...             False                      True
13418     1.653383   0.084198  ...              True                      True
5390      0.323969  -0.833967  ...              True                      True
860      -1.337798  -0.951680  ...              True                      True
7270     -1.337798  -0.598540  ...              True                     False

[12328 rows x 44 columns]

In [ ]:
y_train_perd = model.predict(X_train)
y_test_pred = model.predict(X_test)
y_train_perd

array([3412193.03734085,  538816.57194792, 3107972.2792696 , ...,
        315413.96838231,  792625.57941124, 1096655.71792075])

In [ ]:
y_train

11210    1825000
1347      515000
10363    7500000
316       435000
10638     200000
          ...
5191      665000
13418     249000
5390      250000
860       620000
7270      960000
Name: selling_price, Length: 12328, dtype: int64

In [ ]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

train_mae = mean_absolute_error(y_train, y_train_pred)
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
train_r2 = r2_score(y_train, y_train_pred)



test_mae = mean_absolute_error(y_test, y_test_pred)
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
test_r2 = r2_score(y_test, y_test_pred)



print("=" * 55)
print(f"{'Metric':<10} {'Train':>15} {'Test':>15}")
print("=" * 55)
print(f"{'MAE':<10} {'₹{:,.0f}'.format(train_mae):>15} {'₹{:,.0f}'.format(test_mae):>15}")
print(f"{'RMSE':<10} {'₹{:,.0f}'.format(train_rmse):>15} {'₹{:,.0f}'.format(test_rmse):>15}")
print(f"{'R²':<10} {train_r2:>15.4f} {test_r2:>15.4f}")
print("=" * 55)

print(f"\nInterpretation:")
print(f"  • On average, predictions are off by ₹{test_mae:,.0f} on unseen data")
print(f"  • The model explains {test_r2*100:.1f}% of the variance in car prices")

=======================================================
Metric               Train            Test
=======================================================
MAE               ₹199,220        ₹212,761
RMSE              ₹401,160        ₹445,801
R²                  0.8016          0.7360
=======================================================

Interpretation:
  • On average, predictions are off by ₹212,761 on unseen data
  • The model explains 73.6% of the variance in car prices

# Feature Importance